TASK_TITLE_MIN_LENGTH = 1
TASK_TITLE_MAX_LENGTH = 150

TASK_CONTENT_MIN_LENGTH = 0
TASK_CONTENT_MAX_LENGTH = 5000

USER_USERNAME_MIN_LENGTH = 3
USER_USERNAME_MAX_LENGTH = 30

USER_EMAIL_MIN_LENGTH = 1
USER_EMAIL_MAX_LENGTH = 254

USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 128